### ISSUE TITLE
[Visual Bug] discs don't render horizontally

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TeamMidnightDust/VisualOverhaul#1]
I tested with just `visualoverhaul-1.0.0`, `fabric-api-0.29.1+1.16`, and `autoconfig1u-3.3.1` installed. 

![2021-01-07_22 32 37](https://user-images.githubusercontent.com/618276/103983727-a3068a80-513a-11eb-8177-65c2e6511951.png)
![2021-01-07_22 48 34](https://user-images.githubusercontent.com/618276/103983732-a4d04e00-513a-11eb-921e-8f184cabb606.png)

**Comment by Motschen** [comment]
Are you using any additional resourcepacks?
It's made using minecraft's predicate system, so it will not work if a resourcepack overrides the disc models.
I know it's not ideal, but I couldn't think of doing it another way.

**Comment by supersaiyansubtlety** [comment]
Oh yeah it works if I disable all my resourcepacks, guess one of them was changing the discs without me realizing it. 

Is there a reason you can't just provide your own models+textures independent of the normal disc textures?
