### ISSUE TITLE
Furnace Upper and Lower parts turn black when using it.

### ISSUE THREAD

**Issue by NaythanYT** [TeamMidnightDust/VisualOverhaul#14]
Hi. I downloaded this mod, and everything works. The Furnace though, It looks fine when not in use. But when being used, the upper and lower parts turn black. How do I fix this?
![2021-04-15_11 16 09](https://user-images.githubusercontent.com/82181352/114918593-18d65e00-9ddc-11eb-99a4-f1affd66175a.png)
![2021-04-15_11 16 30](https://user-images.githubusercontent.com/82181352/114918579-16740400-9ddc-11eb-8d3f-4159d4a372e7.jpg)
I'm using Sodium. I think that may be why.

**Comment by Motschen** [comment]
Yes, the furnace model has some issues with sodium. I currently have no clue on how to fix this.

**Comment by NaythanYT** [comment]
> Yes, the furnace model has some issues with sodium. I currently have no clue on how to fix this.

Ah, okay. I guess I could probably remove Sodium until there's a fix for this issue. For now I'm gonna close this until there's a fix with the Model when using Sodium.
