### ISSUE TITLE
[Suggestion] Add compatibility for custom made resourcepacks

### ISSUE THREAD

**Issue by ProboscisMonke** [TeamMidnightDust/VisualOverhaul#16]
As a resource pack creator like me, having the ability to create my own versions of biome dependent textures with this mod would be amazing, and could be useful for modpack creators as well if implemented properly

If there already _is_ a way to do this, please notify me.

**Comment by Motschen** [comment]
This mod doesn't allow you to add biome-depentant textures for items, it just applies the color providers of certain blocks to their item forms.
The feature you're looking for can be achieved with Chime, CITResewn or OptiFine.
