### ISSUE TITLE
[Bug/Incompatibility] Visual Glitch when used with the Jukebox Slab from "Improved Stations"

### ISSUE THREAD

**Issue by BathToast** [TeamMidnightDust/VisualOverhaul#18]
[Improved Stations](https://www.curseforge.com/minecraft/mc-mods/improved-stations) is a mod that creates half slab variants of crafting and work stations in the game.

One of the blocks is the "Jukebox Slab" and this block seems to exhibit some rather odd behavior with Visual Overhaul when its placed in the world as seen in the attached image:
![2021-06-27_22 16 47](https://user-images.githubusercontent.com/66298508/123570191-b8797a80-d795-11eb-8b5e-2b3b22cc96e9.png)

This problem does not cause a crash, and in fact: Works just fine when you attempt to operate it. Its purely a cosmetic bug.

**Comment by Motschen** [comment]
I'm gonna close this, since Improved Stations is not updated past 1.18 and I won't update old versions of VisualOverhaul.
