### ISSUE TITLE
[Compatibility] Jukebox fake block isn't transparent when canvas is installed. 

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TeamMidnightDust/VisualOverhaul#2]
I tested with just `visualoverhaul-1.0.0`, `canvas-mc116-1.0.1267`, `fabric-api-0.29.1+1.16`, and `autoconfig1u-3.3.1` installed.

![2021-01-07_22 53 52](https://user-images.githubusercontent.com/618276/103984211-8c146800-513b-11eb-8f88-cb1e7761b18b.png)

**Comment by Motschen** [comment]
Fixed in the latest commit :)
