### ISSUE TITLE
Otherside disc isn't horizontal

### ISSUE THREAD

**Issue by niraqw15** [TeamMidnightDust/VisualOverhaul#24]
The disc "Lena Raine - otherside" is vertical instead of horizontal in the jukebox. All other discs show up horizontally.
![2022-01-01_17 57 24](https://user-images.githubusercontent.com/22210045/147864103-fc6ac0f5-660f-430f-8ee8-0431f29b6074.png)
The only resource packs selected are those added by Visual Overhaul.

Minecraft 1.18.1
Fabric 0.12.12
Mods:
Fabric API 0.45.0+1.18
Visual Overhaul 4.0.0

**Comment by EndyKuehl** [comment]
I'm having the same problem. My own attempts to fix it broke the mod.
