### ISSUE TITLE
Weird visual glitches and bugs with jukebox and furnace and smoker and blast furnace

### ISSUE THREAD

**Issue by EGOIST1372** [TeamMidnightDust/VisualOverhaul#28]
music discs are not horizontal in jukebox (examples pigstep, otherside, ward)
![2022-02-21_16 49 11](https://user-images.githubusercontent.com/86555131/154964272-e92e654d-ba14-44d5-97eb-ce21caf89127.png)
![2022-02-21_16 49 17](https://user-images.githubusercontent.com/86555131/154964294-67fedb2c-72a1-40da-8ce8-7a1ee5185cd7.png)
![2022-02-21_16 49 28](https://user-images.githubusercontent.com/86555131/154964310-44ae139e-ec8e-44cc-b94b-b6221cd1b6f8.png)

the ore items in blast furnace are not centered
![2022-02-21_16 54 20](https://user-images.githubusercontent.com/86555131/154964604-69c0260f-4c3c-41d8-8c7e-6e16d3d1ea74.png)

weird furnace and smoker visual bugs
![2022-02-21_16 54 39](https://user-images.githubusercontent.com/86555131/154964718-4cb238a4-588b-4c04-b39a-230b849fc40c.png)
![2022-02-21_16 54 59](https://user-images.githubusercontent.com/86555131/154964823-6d869eef-28ae-4349-9be7-ebc647856d27.png)

the only thing that works as intended is brewing stand and jukebox glass top texture, even without any resource pack brewing stand and jukebox texture works
I loaded all 3 resource packs while taking those screenshots and I'm on 1.18.1
with latest sodium and indium
if this mod not compatible with sodium it would be nice to add that to curseforge's description page of the mod

**Comment by Motschen** [comment]
This issue is on Sodium's side, can't do much about that:
https://github.com/CaffeineMC/sodium-fabric/issues/226

**Comment by Motschen** [comment]
Gonna leave this open until it's fixed on Sodium's side

**Comment by EGOIST1372** [comment]
you fixed the music discs problem with version 4.1.0 - 1.18.2
![image](https://user-images.githubusercontent.com/86555131/157940994-81cbf893-95a6-43d7-a29d-f984b4353d46.png)
thanks <3

**Comment by EGOIST1372** [comment]
but smoker and furnace and blast furnace still have visual glitches

**Comment by Motschen** [comment]
As I said, there's sadly not much I can do about that.
It's a Sodium bug.

**Comment by EGOIST1372** [comment]
yeah I know, sadly
we all waiting for it to get fix ;-;

**Comment by olivergame** [comment]
weird thing is on the single play i see no glitch and on a server i do see a glitch

**Comment by Motschen** [comment]
Fixed in newer Sodium versions
