### ISSUE TITLE
[Request] support for glass bottles

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TeamMidnightDust/VisualOverhaul#3]
Just a minor visual thing, but glass bottles seem to use a default red texture. 
It would be nice if they were given their own, transparent texture. 
![2021-01-07_22 58 44](https://user-images.githubusercontent.com/618276/103984577-3ab8a880-513c-11eb-9697-8fd884d2f80a.png)

**Comment by Motschen** [comment]
It's not the glass bottles that are red, it's just that the default brewing stand texture is still loaded and being displayed. You need to activate the nopotionbottles resourcepack provided with this mod, it should just show up with your other resourcepacks in the resourcepack selection screen.

**Comment by supersaiyansubtlety** [comment]
Oh I see, that explains why the other potion textures looked slightly off as well. 
Maybe change the resourcepack description to "Removes the *original/static* potions from the brewing stand texture. " or something and put a note on the mod page about it?

**Comment by supersaiyansubtlety** [comment]
Actually how did you go about making the brewing stand a separate resourcepack as opposed to a standard mod resource?
I have a few alternate textures for my auto crafter block that I'd like to bundle with the mod.

**Comment by Motschen** [comment]
Take a look at the last lines of this class: https://github.com/TeamMidnightDust/VisualOverhaul/blob/main/src/main/java/eu/midnightdust/visualoverhaul/VisualOverhaulClient.java

**Comment by supersaiyansubtlety** [comment]
Oh neat, thanks!
