### ISSUE TITLE
[Bug/Incompatibility] Incompatibility with CIT Resewn

### ISSUE THREAD

**Issue by Fiopon** [TeamMidnightDust/VisualOverhaul#31]
Practically disables CIT Resewn for any items in GUI. In hand, dropped, and held by entities (including Armor Stands and Item Frames) show the item as intended by CIT Resewn, but items inside player inventory and chests appear as vanilla. Interestingly, CIT Resewn appears to work with items in brewing stands.

Please fix

**Comment by Motschen** [comment]
I actually have no clue what could be causing this, since I only change something related to model overrides for music disc items.
Could you tell me which pack you are using and which items it happens with?
