### ISSUE TITLE
the enchanted shine is buggy, it ripples

### ISSUE THREAD

**Issue by aexplousea** [TeamMidnightDust/VisualOverhaul#32]
there is a wizard's book in your hand, a potion, a bubble of experience, enchanted tools and armor - it will be seen that the enchanted shine is applied unevenly and buggy. Also, this problem can be observed when the potion is in the potion maker

**Comment by Motschen** [comment]
This is actually a vanilla issue, it's just very noticable with VisualOverhaul's brewing stand overhaul
