### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [TeamMidnightDust/VisualOverhaul#35]
Do you plan on updating the mod, and if it already works would you be able to mark it on modrinth?

**Comment by Motschen** [comment]
I'll skip 1.19.3, though I just released a version for 1.19.4!

**Comment by ViTulyankin** [comment]
@Motschen, any plans to port it on 1.19.3 eventually?

**Comment by Motschen** [comment]
Nope, I only support the latest version of Minecraft.

**Comment by ViTulyankin** [comment]
And skipped the one that was "the lastest" for over 4 months... It's a pity

**Comment by Motschen** [comment]
> And skipped the one that was "the lastest" for over 4 months... It's a pity

Why would you use 1.19.3? It doesn't bring any substantial new features and has less mods than 1.19.2.
1.19.4 at least adds the Cherry Grove Biome, arrow key navigation and tab support, which are features I've been waiting for for a long time.
Also, I have a lot of mods to maintain, as well as having real life, so I sometimes just don't get around to updating them.

**Comment by ViTulyankin** [comment]
There are no problem that you won't port it, you don't really have to do anything. Port to 1.19.4 is already great, but i have a big collection of mods on 1.19.3, most of which came only on this version. Maybe when most of them will be updated, I will use 1.19.4 :)

Btw, 1.19.3 have a killer feature over .2 – new creative screen
