### ISSUE TITLE
Icons on menu buttons overlapping with the text

### ISSUE THREAD

**Issue by Uncroww** [TeamMidnightDust/VisualOverhaul#39]
Hi !
Everything's said in the title, I'll just add a screenshot there : 
![image_2023-05-07_130657378](https://user-images.githubusercontent.com/115645286/236673769-3e2928fd-d71f-4f4a-b3fa-2a275b9ea67a.png)
(Direct Connection and refresh a little bit)
![image_2023-05-07_130745235](https://user-images.githubusercontent.com/115645286/236673801-85c252dc-f662-4963-91a1-81cfd6c376e6.png)
(Re-create)

**Comment by Motschen** [comment]
This is kinda intentional, I think it looks quite cool.
You can create an icon pack yourself, where you just don't include the buttons the text would overlap on.
