### ISSUE TITLE
Weird Config Format

### ISSUE THREAD

**Issue by ZaneDragonBorn** [TeamMidnightDust/VisualOverhaul#4]
Seems to be a problem with the config turning into a mess.
![image](https://user-images.githubusercontent.com/68198648/104663271-9df58e00-569a-11eb-98ae-dc6782fa95d8.png)

**Comment by Motschen** [comment]
Oh yes, I forgot to add translations...
Will be fixed in the next update.

**Comment by Motschen** [comment]
Fixed in v2.0.0 :)
