### ISSUE TITLE
CC:T compitability issue

### ISSUE THREAD

**Issue by SirEdvin** [TeamMidnightDust/VisualOverhaul#49]
So, with VisualOverhaul installed, CC:T gui screens for computers and turtle doesn't get focus, when you first open them. There is possible to click on gui screen with mouse to set focus for this screen, but this is not how it should works.

[Mirror issue in CC:T repository](https://github.com/cc-tweaked/CC-Tweaked/issues/1538)

**Comment by SquidDev** [comment]
I've left some additional notes on the CC:T issue, but I think the easiest fix here is for `VisualOverhaul` to not call `init` inside the constructor of `IconicButtons`:

https://github.com/TeamMidnightDust/VisualOverhaul/blob/e9539ba28fa60f023ff910480bbce31ec79de19b/common/src/main/java/eu/midnightdust/visualoverhaul/IconicButtons.java#L26-L28

This ensures that no virtual methods are called when constructing a `PressableWidget`, and so you don't run the risk of accessing uninitialised state.

**Comment by Motschen** [comment]
Thanks for the help, SquidDev!
