### ISSUE TITLE
Theoretically Client-Side only mod isn't Client-Side only

### ISSUE THREAD

**Issue by milkev** [TeamMidnightDust/VisualOverhaul#5]
Is this mod capable of becoming client side only?
it works perfectly fine in singleplayer, however has no effect when joining a vanilla server.

**Comment by Motschen** [comment]
Sadly it isn't possible to make this a client-only mod, because the server doesn't send the required data to the client.

**Comment by milkev** [comment]
thats unfortunate, but understandable, thanks for letting me know
