### ISSUE TITLE
[Feature] make option to disable Icons

### ISSUE THREAD

**Issue by Aces-and-Jacks** [TeamMidnightDust/VisualOverhaul#50]
So I use a resource pack that ads Icons which is named "Icons". When I enable this mod it overlaps with the resource pack. There's no resource pack or config I can disable, so I was wondering if that could be added

**Comment by Motschen** [comment]
There IS a config, where everything about the mod can be configured. For some reason, it currently doesn't automatically get integrated into ModMenu on the Quilt version, so try using the Fabric version instead.

**Comment by Aces-and-Jacks** [comment]
Well I can open up the config file but I don't know which option turns off the Icons

**Comment by Motschen** [comment]
Use the in-game config, it's explained there very clearly

**Comment by Motschen** [comment]
The option is called buttonIcons, set it to false to disable them

**Comment by Aces-and-Jacks** [comment]
I made a fabric instance and added midnightlib, Fabric API, visual overhaul, and modmenu on 1.20.1 but I didn't see a config option and I didn't see any buttonIcon option in the config file

**Comment by Motschen** [comment]
See #37
