### ISSUE TITLE
Jukebox Stays Powered

### ISSUE THREAD

**Issue by Boobies** [TeamMidnightDust/VisualOverhaul#53]
With Visaul Overhaul, jukeboxes stay powered after the disc has finished playing. This makes it impossible to properly interact with hoppers.

**Comment by XavierBit** [comment]
I can confirm this behavior. Automatic juke boxes aren't possible this way as the hopper stays locked and doesn't drain the disc which has been implemented with Minecraft 1.19.x.

**Comment by FatPorpoise** [comment]
Yup, confirmed, made me sad when I discovered that
