### ISSUE TITLE
[Crash] on dimension change

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TeamMidnightDust/VisualOverhaul#6]
On my server, my friend and I have the same client mod set, but our configs may differ slightly. 

My friend was getting crashes whenever they changed  dimensions, both when dying in the nether and respawning in the overworld, and when using a nether portal. 

I have no issues. 

Here are logs:

[nether-death-latest.log](https://pastebin.com/JJ5cG772)
[nether-portal-latest.log](https://pastebin.com/hKpKNSFV)

Here's the complete contents of my mods folder (sorry but I've updated some mods since then so it doesn't match the set from the logs exactly)

**Comment by Motschen** [comment]
Fixed in v3.0.0
