### ISSUE TITLE
Null SoundInstance in MixinSoundSystem.vo$onPlayRecordSound without a null check

### ISSUE THREAD

**Issue by SilverDavidMC** [TeamMidnightDust/VisualOverhaul#60]
`MixinSoundSystem.vo$onPlayRecordSound` doesn't have a null check, despite `SoundInstance` being capable of being set to null through a Forge event.

[crash-2023-11-22_11.17.59-client.txt](https://github.com/TeamMidnightDust/VisualOverhaul/files/13434262/crash-2023-11-22_11.17.59-client.txt)

**Comment by SaraXianLin** [comment]
I think I am having the same issue, this mod is crashing The Aether and Alex caves mods:

**The-Aether-Team:**
I think this is an issue with Team Midnight Dust's Visual Overhaul mod, they should be checking if soundInstance != null here: https://github.com/TeamMidnightDust/VisualOverhaul/blob/e9539ba28fa60f023ff910480bbce31ec79de19b/common/src/main/java/eu/midnightdust/visualoverhaul/mixin/MixinSoundSystem.java#L23C1-L26C10

Here you can find the crash and latest log:

https://github.com/The-Aether-Team/The-Aether/issues/1846

Please let me know if you need anything else @TeamMidnightDust

Thank you,
Regards
Sarah
