### ISSUE TITLE
Failed to send too large packet

### ISSUE THREAD

**Issue by IBeiKui** [TeamMidnightDust/VisualOverhaul#63]
this issue kept kicking the both the host and the guest out of the world, showing a message read "Failed to sent packet
java.lang.IndexOutOfBoundsException: readerIndex(23) + length(8) exceeds writerIndex(23): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 23, widx: 23, cap: 23)" for host and "Server sent an invalid packet" for guest.

Until I found this mod in debug.log,I removed it, then everything was fine.

[debug.log](https://github.com/TeamMidnightDust/VisualOverhaul/files/14222318/debug.log)

**Comment by Motschen** [comment]
Seems to be the same as #45
