### ISSUE TITLE
[Suggestion] Overhaul Blast Furnace & Smoker

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [TeamMidnightDust/VisualOverhaul#7]
Do the same with the other furnace types as you did with the furnace. :-)

**Comment by Motschen** [comment]
Yeah, that is planned, however it will take some time, since making it look good with the other furnace types is time consuming :)

**Comment by Motschen** [comment]
If I get to do this I will also add compatibility with [Kiln](https://www.curseforge.com/minecraft/mc-mods/kiln-fabric).

**Comment by RDKRACZ** [comment]
What about compatibility with https://www.curseforge.com/minecraft/mc-mods/sentimentality-2
![image](https://user-images.githubusercontent.com/43277609/111156686-51450b00-8596-11eb-9669-a27375d7dfe9.png)
This seems like a lot of work when done manually but I'm sure it can be (probably already is) somewhat automated.

**Comment by Motschen** [comment]
The furnaces all look like the default variants, exept for the colors of the textures, so I could use the same model for all of these and just apply a different texture. Shouldn't be too complicated, but we'll see.

**Comment by Motschen** [comment]
Done in 4.0.0 ;)
