### ISSUE TITLE
Log exploded when rendering modified blocks

### ISSUE THREAD

**Issue by KigeYark** [TeamMidnightDust/VisualOverhaul#72]
Every time modified blocks like furnaces and brewing stands are rendered, a log line will output through `STDOUT`.

### Minecraft Version
1.21

### Modloader
Fabric 0.15.11 with Fabric API 0.100.3

### Mod Version
5.2.0

### Log
[latest.log](https://github.com/user-attachments/files/15898115/latest.log)

**Comment by Motschen** [comment]
I just noticed this myself. Fixed!
